### ISSUE TITLE
Causes crash and reloading of QGIS 2.18.16 to crash

### ISSUE THREAD

**Issue by scabecks** [tarot231/CalculateGeometry#2]
Installing the plugin on 2.18.16 (nightly build) causes QGIS to crash. QGIS will not restart until I manually remove the plugin contents from the plugins folder.

**Comment by tarot231** [comment]
Try with stable build. Normally, python only throws an error and does not crash

**Comment by tarot231** [comment]
Try with stable build. Normally, python only throws an error and does not crash.

**Comment by tarot231** [comment]
Dropped QGIS 2
