### ISSUE TITLE
After using on one writeable layer it thinks it can operate on read-only layers.

### ISSUE THREAD

**Issue by AlisterH** [tarot231/CalculateGeometry#3]
It seems like it is supposed to only support writeable layers (it is greyed out in the menu for read-only layers).  But after using for a writeable layer it is no longer greyed out for read-only layers.

**Comment by AlisterH** [comment]
Also, the plugin description and docs could make it clear that the plugin writes to the layer attribute table (rather than just reporting the numbers to the user).

But if you were keen you might want to consider some feature enhancements e.g.:
- ability to add to a new field, rather than editing an existing one
- an option to add to the layer as a virtual field
- an option just to present the results in a window, without writing them to the layer
- an option to report the total, if multiple features are selected

**Comment by tarot231** [comment]
You're right, but I also want to keep the UI as simple as possible. As of now, I consider this almost complete.
