### ISSUE TITLE
No dropdown for fields

### ISSUE THREAD

**Issue by dgva** [tarot231/CalculateGeometry#4]
On QGIS 3.16, the default version is 0.5.1, and the experimental is the one currently on this repo. 
On the older version it was possible to select the fields using a dropdown menu. That feature is no longer present on the newer version.
Could this make a return? Even though the option to create directly new fields is good, it is necessary to write the existing fields with the exact name, and that creates a bit more work to make sure the field name is exactly the same.

**Comment by tarot231** [comment]
I understand. I'll update it with editable combo box.

**Comment by tarot231** [comment]
Applied in v0.6.1
